#!/bin/sh

#
# Create apps for a user's subaccounts
#
# Assumes username format user#s# and domain namespace == username
#

for x in $( seq 1 10 )
do
	for y in $( seq 1 20 )
	do
		for z in $( seq 1 10 )
		do
			./create-app.sh user${x}s${y} java${z} "jbossews-2.0"
		done
	done
done
